services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      # - xpack.security.enabled=false

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5000:5000"
      - "5044:5044"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    build:
        context: ./filebeat
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
        - ./nodejs-logs:/src/logs
    depends_on:
        - logstash
        - nodejs-app

  nodejs-app:
    build:
      context: ./app 
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - "3002:3002"
    volumes:
        - ./nodejs-logs:/src/logs

volumes:
  elasticsearch_data:
      driver: local